[build-system]
#requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "satellite-resources"
authors = [{name = "John Cintineo", email = "john.cintineo@noaa.gov"}]
dynamic = ["version", "description"]
